### ISSUE TITLE
Weekend Span of tasks

### ISSUE THREAD

**Issue by GasparYYC** [ogobrecht/apex-plugin-dhtmlx-gantt#2]
Enhancement Request:
Have the option to exclude weekend from the tasks, so if the tasks spans across the weekend extend it over the weekend not counting the days. 
Best case scenario is to is to have the Option to exclude weekends from tasks (although that is probably more application logic than plug-in functionality)

thank you for your consideration

**Comment by ogobrecht** [comment]
Hi @GasparYYC,

this works out of the box with the help of the extensive dhtmlxGantt API - see region attributes of Gantt region and put under "Before Init JS Code":

```js
// exclude weekends from work time calculation: https://docs.dhtmlx.com/gantt/desktop__working_time.html
gantt.config.work_time = true;

// specifiy css class for task cell: https://docs.dhtmlx.com/gantt/api__gantt_task_cell_class_template.html
gantt.templates.task_cell_class = function(task, date){
    if ( gantt.config.scale_unit === "day" && !gantt.isWorkTime(date) )
        return "no_work_time";
    return "";
};

// specifiy css class for scale cell: https://docs.dhtmlx.com/gantt/api__gantt_scale_cell_class_template.html
gantt.templates.scale_cell_class = function(date){
    if ( gantt.config.scale_unit === "day" && !gantt.isWorkTime(date) )
        return "no_work_time";
    return "";
};
```

Then define on your page css the inline styles for the new class:

```css
.gantt_scale_cell.no_work_time,
.gantt_task_cell.no_work_time { 
    background-color: #f4f7f4;
}

/* when row is selected we don't want to have a background color */
.gantt_selected .gantt_scale_cell.no_work_time,
.gantt_selected .gantt_task_cell.no_work_time {
    background-color: transparent;    
}

/* ATTENTION: theme dependend - works for default theme - please correct color for other theme or simply delete */
.gantt_scale_cell.no_work_time { 
    border-bottom: 1px solid #cecece;
}
```

Although it is working out of the box I can clearly see that this is a common requirement. I will provide an option for this and a new plugin version the next weeks.

Best regards
Ottmar
